### ISSUE TITLE
Various typos 

### ISSUE THREAD

**Issue by c0nb4** [TUB-DVG/wissen-digital-ewb#106]
## Description of the issue

There are a few typos on the webpage. Please fix them 

On page Anwendungsfälle: 

![grafik](https://github.com/user-attachments/assets/98acec2b-3e13-4ad5-97dd-8993f7cb433b)

eFfekte -> Effekte 

![grafik](https://github.com/user-attachments/assets/f73f7a1a-d86c-4d9c-9428-d3c1408e5f69)

-> Gesamter  Stromverbrauch -> Gesamstromverbrauch 

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](../CONTRIBUTING.md)
- [ ] I have checked that there is no issue already opened about this bug

**Comment by c0nb4** [comment]
Error in translation in tool list. 

![grafik](https://github.com/user-attachments/assets/bafac3b8-4e73-4c5f-a764-611569fd3abe)

**Comment by Cudok** [comment]
"concrete use case' should be "specific use case"?
![446cf9b6-e5b9-4a8c-acee-03954ec14502](https://github.com/user-attachments/assets/79b70c77-b82a-40b5-bad6-8a5c6871a300)
![63986c65-e933-4535-8f3e-4656eb316834](https://github.com/user-attachments/assets/79db1fdf-2f62-409a-8668-c8b7b8bf306c)

**Comment by Cudok** [comment]
more inconsistencies in capital/lower letters
![84088234-11b3-4367-ba7a-20a75855da5a](https://github.com/user-attachments/assets/2efd9293-f1b2-4b84-817d-877f213500bd)

**Comment by c0nb4** [comment]
Solved with attached PR
