### ISSUE TITLE
Update Numpy

### ISSUE THREAD

**Issue by KaifengXuuu** [TUB-DVG/wissen-digital-ewb#130]
## Update numpy==1.24.3 >> 2.0.0   
    wetterdienst 0.88.0 depends on numpy<1.27 and >=1.22
    pandas 2.2.2 depends on numpy>=1.22.4
Current version of wetterdienst do not support latest numpy. Try to update wetterdienst first.

## Solution
update Wetterdienst
update Numpy

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](../CONTRIBUTING.md)
- [ ] I have created a branch for my feature

**Comment by KaifengXuuu** [comment]
The latest version of wetterdienst is 0.95.1 while current using version is 0.88.0
After testing in jupyter notebook, the wetterdienst== 0.95.1 is working well but the API parameters have been changed a little:
- previous parameter of datasets in wetterdienst==0.88.0 is 
```
"TEMPERATURE_AIR_MEAN_200"
```
- the available parameters in new version of wetterdienst==0.95.1 are
```
TEMPERATURE_AIR_2M
TEMPERATURE_AIR_MEAN_0_05M
TEMPERATURE_AIR_MEAN_2M
TEMPERATURE_AIR_MEAN_2M_LAST_24H
```

Which one should i use? Please give me some advice. Thanks.
@c0nb4

**Comment by c0nb4** [comment]
TEMPERATURE_AIR_2M would be my suggestion.
