### ISSUE TITLE
Review Changes from Design Backlog

### ISSUE THREAD

**Issue by expeditionengineer** [TUB-DVG/wissen-digital-ewb#132]
# Review of design changes
The listing page looks for me like this:
![grafik](https://github.com/user-attachments/assets/d21b9893-c596-4e7a-bb38-5d26421599b8)
-> search bar is too big, please check prototype on figma
-> each listing item is shown in a separate line
-> move the text above the accordion: 
"Die hier vorgestellten digitalen Werkzeuge entsprechen den Werkzeugen, die im Rahmen der Auswertung des Fragebogens der wissenschaftlichen Begleitforschung der Forschungsinitiative Energiewendebauen von 2021 und 2023 erfasst wurden. Alle digitalen Werkzeuge werden dementsprechend von Projekten eingesetzt, entwickelt oder weiterentwickelt, die im Rahmen der Forschungsinitiative Energiewendebauen gefördert werden."
![grafik](https://github.com/user-attachments/assets/1aa12270-2ff1-4124-8381-2935a0d699ac)
-> When accordion is expanded replace the "+" by a "-"
-> can you add the 2 buttons:
![grafik](https://github.com/user-attachments/assets/a41792bd-c327-46aa-a22b-02d2d836961b)
Can you fix the spacing here? There should be the same distance to the green border for the image like for the the description text

**Comment by nlongn22** [comment]
> -> can you add the 2 buttons:

> Can you fix the spacing here? There should be the same distance to the green border for the image like for the the description text

Can you please explain more these parts and where they are located? I don't understand.

Everything else is fixed on the branch `filip-figma-backlogs`.

**Comment by expeditionengineer** [comment]
Sorry i forgot to add a screenshot. Here is the screenshot from the page "Negative Umweltwirkungen"
![grafik](https://github.com/user-attachments/assets/3e65fe16-f6dd-46b2-8eb4-ff620071b717)

**Comment by nlongn22** [comment]
I just checked and I already added it before, the image looks fine to me:
![image](https://github.com/user-attachments/assets/f4c30e83-fa39-497b-a591-7785ac30ee23)

**Comment by expeditionengineer** [comment]
Could you change it so it looks like in the figma: 
![grafik](https://github.com/user-attachments/assets/3fb853f4-f4d2-4b06-bded-3e8d4a81e905)

**Comment by expeditionengineer** [comment]
So the white padding inside the green box should have the same size everywhere. Here is the figma link: https://www.figma.com/design/9isFFZdptnsTNPVPhOcC5d/Wissensplattform-Entwurf?node-id=631-3301&node-type=canvas&t=HaSzC5vwJEn0whYv-0

**Comment by nlongn22** [comment]
Ah I get it now, thanks. I'll get to it

**Comment by nlongn22** [comment]
@expeditionengineer it should be okay now
