### ISSUE TITLE
Move Data from weatherdata table to Datasets and Tools table

### ISSUE THREAD

**Issue by expeditionengineer** [TUB-DVG/wissen-digital-ewb#142]
To improve the structure of the database the weatherdata-table should be deleted. The data from here should be moved to CollectedDatasets and Tools.

**Comment by c0nb4** [comment]
When working on this issue, can you keep this one in mind: https://github.com/TUB-DVG/wissen-digital-ewb/issues/18

**Comment by expeditionengineer** [comment]
I started looking into the migration of the weatherdata model into the 2 other models. There are a few attributes where im not sure were to put them. Here is a mapping. 
# Mapping of weatherdata to tools and datasets
Attribute Name Weatherdata -> Attribute Name Tool / Attribute Name CollectedDataset
data_service -> name/nameDataset
short_description -> shortDescription/shortDescriptionDe
provider -> provider/ ?
further_information -> furtherInformation/ ?
data_url -> ? /referenceLink
logo_url -> ? / ?
applications -> areaOfApplication/

Please note this is still work in progress
