### ISSUE TITLE
Update of Tools

### ISSUE THREAD

**Issue by c0nb4** [TUB-DVG/wissen-digital-ewb#164]
## Description of the issue

This issue is considered a general issue, regarding the update of tools. All issues, feedback, and other remarks are listed. 

## Tools

1. FMI: _(Please note, that it is perhaps misleading to list FMI unter “digital tools” and mention it as “Command line”, it would be perhaps better to reference it as a “standard” and using an “API)_
 2. Casadi,  _CasADi. Fwiw, it is also unsuable for (co-)design._
3. Enercalc - wrong tool, update to info from https://ingefo.de/Werkzeuge/EnerCalC/ 
4. EarthEnergyDesigner - _Please use the logo but change the text for “last update” in both pictures from ”2019-04-01” To ”2024-03-27” or “ongoing”_
5. Add Geo-HANDlight, see data by Daniel B. 
6. Update of logos for Design Builder 
7. Update of logo for TRYNSYS 
8. .Update ArcGIS Logo and rename to  "Esri ArcGIS". 
9. Delete Comsol Logo (but keep content)

**Comment by c0nb4** [comment]
Data for Geo-HANDlight. 
[tools_factsheet_GEOHANDlight.docx](https://github.com/user-attachments/files/17570367/tools_factsheet_GEOHANDlight.docx)

**Comment by c0nb4** [comment]
Form Docker to Host Shell: docker cp [container-name]:<path-to-file> 

- hint pwd to 

From server to pc: 
scp <server>:/path/20241114_Tools.xlsx

**Comment by expeditionengineer** [comment]
- brought new images onto the server
- imported new tools excel file

**Comment by expeditionengineer** [comment]
- Made data_import of tools more robust: Value in `lastUpdate` is checked against a regular expression of the form YYYY-mm-dd or YYYY.mm.dd and only the substring, which matches the expression is then taken for further processing. In that way errors can be avoided, which appeared when other characters were present.
