### ISSUE TITLE
Bugs in the navbar

### ISSUE THREAD

**Issue by expeditionengineer** [TUB-DVG/wissen-digital-ewb#167]
- When zoom is activated in the browser, the dropdown menu lies over the navbar-item:
![grafik](https://github.com/user-attachments/assets/09c655dc-5080-49c4-9932-54feffd3a46b)
- nav item text should stay black at hover:
![grafik](https://github.com/user-attachments/assets/21082bf6-2704-494d-bb8a-09499e1fb0bf)

**Comment by c0nb4** [comment]
Third: In the dropwdown Menu, the ICON near the navbar element should be colored, when hoovering or hoovering dropwdown.

**Comment by expeditionengineer** [comment]
Thanks a lot. Could you also check the last point, that the icon should be colored when the mouse is in the dropdown-menu?
For me it lis not colored 
![grafik](https://github.com/user-attachments/assets/77da6259-28a3-4943-9463-dd24988b2690)
