### ISSUE TITLE
Copyright page 

### ISSUE THREAD

**Issue by c0nb4** [TUB-DVG/wissen-digital-ewb#177]
## Description of the issue

Include a static copyright page, so we can link the logo use, e.g. in case of softare from third parties. 

## Ideas of solution

Copy page "Datenschutzhinweis" and add text for: 

- Python
- Autodesk 

## Workflow checklist

- [X] I am aware of the workflow in [CONTRIBUTING.md](../CONTRIBUTING.md)
- [ ] I have created a branch for my feature

**Comment by nlongn22** [comment]
Hi, you can find the template ready on the filip-copyright-template branch.

**Comment by c0nb4** [comment]
Can you please open a PR and link it? Thank you.

**Comment by nlongn22** [comment]
#183 

by the way I put just placeholder text there, do we have already a particular text for Python and Autocad?

**Comment by c0nb4** [comment]
Please take these two examples first, add one for the german and one for the english version. 

German text for Intro: 

Urheber- und Kennzeichenrecht

Der Herausgeber ist bestrebt, in allen Publikationen die Urheberrechte der verwendeten Bilder, Grafiken, Ton- und Videodokumente sowie Texte zu beachten, von ihm selbst erstellte Bilder, Grafiken, Ton- und Videodokumente sowie Texte zu nutzen oder auf lizenzfreie Grafiken, Ton- und Videodokumente sowie Texte zurückzugreifen.

Alle innerhalb des Internetangebotes genannten und ggf. durch Dritte geschützten Marken- und Warenzeichen unterliegen uneingeschränkt den Bestimmungen des jeweils gültigen Kennzeichenrechts und den Besitzrechten der jeweiligen eingetragenen Eigentümer. Allein aufgrund der bloßen Nennung ist nicht der Schluss zu ziehen, dass Markenzeichen nicht durch Rechte Dritter geschützt sind!

Das Copyright für veröffentlichte, vom Herausgeber selbst erstellte Inhalte und Objekte bleibt allein beim Herausgeber der Seiten. Eine Vervielfältigung, Verarbeitung, Einspeicherung oder Verwendung solcher Grafiken, Ton- und Videodokumente sowie Texte in anderen elektronischen oder gedruckten Publikationen ist ohne ausdrückliche Zustimmung des Autors nicht gestattet. Unberührt davon bleibt das Kopieren und Herunterladen für den privaten, wissenschaftlichen und nicht kommerziellen Gebrauch. Wir erlauben ausdrücklich und begrüßen das Zitieren unserer Dokumente und Webseiten sowie das Setzen von Links auf unsere Website.

English text for intro: 

The publisher endeavors to observe the copyrights of the images, graphics, sound and video documents, and texts used in all publications; to use images, graphics, sound and video documents, and texts created by the publisher; or to use license-free graphics, sound and video documents, and texts.

All brands and trademarks mentioned within the website and possibly protected by third parties are subject without restriction to the provisions of the applicable trademark law and the ownership rights of the respective registered owners. The fact alone that a trademark appears within a text does not imply that it is not protected by the rights of third parties!

The copyright for published content and objects created by the publisher themselves remains solely with the publisher of the pages. Any duplication, processing, storage or use of objects such as diagrams, sound and video documents, or texts in other electronic or printed publications is not permitted without the author's agreement. This does not apply to copying and downloading for private, scientific and non-commercial use. We expressly permit and welcome the citing of our documents and web pages as well as the linking to our website.
