### ISSUE TITLE
Wissensplattform Lite

### ISSUE THREAD

**Issue by c0nb4** [TUB-DVG/wissen-digital-ewb#179]
## Description of the issue

To reduce effort for maintenance after the project is endend, we'd like to have a Wissensplattform lite. 

- Get rid of DWD and wetterdienstintegration
- Get rid of Cesium application 

## Ideas of solution

- Remove in headers / links 
- Remove apps 
- Remove from pyproject 

--> Double check if polars installation is still needed. 

## Workflow checklist

- [x] I am aware of the workflow in [CONTRIBUTING.md](../CONTRIBUTING.md)
- [x] I have created a branch for my feature

**Comment by KaifengXuuu** [comment]
For getting rid of `wetterdienst` and `polars`:    
In the app of Wärmelast Approximation there is a dropdown switch which has an option leading to wetterdienst API. I have closed that option and delete the imports of `wetterdienst`. After testing, the webpage and application both work well after removing `wetterdienst`and `polars` in pyproject.toml.   
For possible further datasets in the future the functions and web structure are remained and unavailable right now.

**Comment by KaifengXuuu** [comment]
as written above :
```
Please take the TRY data from here instead in implement it: https://github.com/RWTH-EBC/districtgenerator/tree/master/districtgenerator/data/weather
```
Does it means to visiting and operating the data in the link above with our Django web App automatically and dynamically but not download the Try Data and manually filter them as we did before? @c0nb4
