### ISSUE TITLE
Reformat according to pylint ci pipeline txt file

### ISSUE THREAD

**Issue by c0nb4** [TUB-DVG/wissen-digital-ewb#27]
Review this: https://github.com/TUB-DVG/wissen-digital-ewb/blob/main/lint.txt 

Apply automatic linting to fix the errors, you can also check out: https://www.trycursor.com/

**Comment by nlongn22** [comment]
I ran djlint and black through the project and it looks like that style format issues are solved.
But the `list.txt` shows errors such as incorrect naming cases, missing doc-strings or unused imports and variables. I'm looking at how to automate them safely so the project doesn't break:

1. Tried CursorAI for automated fix but I think the file content is too large and the results are not always correct.

**Comment by c0nb4** [comment]
@nlongn22 can you push a branch where the style format issues are fixed?

**Comment by c0nb4** [comment]
Included in CI pipeline.
