### ISSUE TITLE
Criteria Catalog: Search bar does not work

### ISSUE THREAD

**Issue by Privacy-Icons** [TUB-DVG/wissen-digital-ewb#43]
## Description of the issue

Search on criteria catalog does not work

**Comment by c0nb4** [comment]
@Privacy-Icons I cannot reproduce the error. Can you please specify?

**Comment by Privacy-Icons** [comment]
Seemed to be an issue with my browser maybe. Works for me now .. not sure what the issue was, sorry.

**Comment by c0nb4** [comment]
Thanks for the update :)
