### ISSUE TITLE
Criteria Catalogue: 8. "Betroffenenrechte" does not show any content

### ISSUE THREAD

**Issue by Privacy-Icons** [TUB-DVG/wissen-digital-ewb#62]
## Description of the issue

For unclear reasons "Betroffenenrechte" does not show any content. I checked the latest table I send youon Monday (mail v. 09.09.)  and this includes all content.

**Comment by expeditionengineer** [comment]
There is a inconsistency in the data file I imported:
![grafik](https://github.com/user-attachments/assets/23e5d748-1d2e-4a16-ad8b-9b38cb326111)
There are multiple instances of the same ID 137 and 138.
i will fix the double entries and try to import the result
