### ISSUE TITLE
Update style of "Anwendungsfälle" 

### ISSUE THREAD

**Issue by c0nb4** [TUB-DVG/wissen-digital-ewb#86]
## Description of the issue

Describe the problem in as much detail as possible.

## Ideas of solution

New Style: 
![grafik](https://github.com/user-attachments/assets/e447fd79-fa8d-464b-9354-7aa2c89e6fda)

Graphics attached. 
![Info](https://github.com/user-attachments/assets/897b8d34-edfc-49ac-b34b-994f73e88cd4)
![SRI](https://github.com/user-attachments/assets/fac2b05f-a7aa-4edd-a573-db7a36888abd)

Please use the same picture in both, german and english. 

## Workflow checklist

- [ ] I am aware of the workflow in [CONTRIBUTING.md](../CONTRIBUTING.md)
- [ ] I have created a branch for my feature

**Comment by nlongn22** [comment]
Pushed to branch `filip-update-usecases`. Only thing missing is the image - @expeditionengineer can you please help me with the image above? When I put the image tag with src attribute inside the `view.py`, it throws an error.

**Comment by expeditionengineer** [comment]
thanks, i check your code
